name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploying to Google App Engine
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Google Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to App Engine
        run: |-
          gcloud app deploy app.yaml --project=${{ secrets.GCP_PROJECT_ID }} --quiet
